"""Added pairs table

Revision ID: 7c988fb94a4e
Revises: 
Create Date: 2023-02-10 21:43:52.579908+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c988fb94a4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('datetime', sa.String(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pairs_id'), 'pairs', ['id'], unique=False)
    op.create_index(op.f('ix_pairs_name'), 'pairs', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pairs_name'), table_name='pairs')
    op.drop_index(op.f('ix_pairs_id'), table_name='pairs')
    op.drop_table('pairs')
    # ### end Alembic commands ###
